# Generated by Django 3.1 on 2022-08-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ies_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SP',
        ),
    ]
