# Generated by Django 4.1.2 on 2022-10-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('date_create', models.DateField(null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('TIN', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_p', models.CharField(blank=True, max_length=20, null=True)),
                ('station_p', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('date_create', models.DateField(null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log_dwh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(max_length=40)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('date_create', models.DateField(null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(unique=True)),
                ('type_name', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('date_create', models.DateField(null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(unique=True)),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('measure', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('date_create', models.DateField(null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwh.brands')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwh.types')),
            ],
        ),
        migrations.CreateModel(
            name='Last_download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=30)),
                ('last_download', models.DateTimeField(null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('date_create', models.DateField(null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('table_name', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='Customers_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(unique=True)),
                ('name_good', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sum', models.BigIntegerField(null=True)),
                ('date_deal', models.DateField(null=True)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('dataset', models.IntegerField(null=True)),
                ('last_user', models.CharField(blank=True, max_length=20, null=True)),
                ('last_changed', models.DateTimeField(null=True)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwh.customers')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dwh.types'),
        ),
    ]
